#!/usr/bin/env ruby

mod 'puppetlabs-apache', '3.4.0'
mod 'puppet-collectd', '10.1.0'
mod 'puppetlabs-stdlib', '5.1.0'
mod 'puppetlabs-concat', '5.1.0'
mod 'puppetlabs-apt', '6.1.1'
mod 'puppetlabs-translate', '1.2.0'
mod 'stahnma-epel', '1.3.1'
mod 'dwerder-graphite', '7.3.0'
mod 'puppet-grafana', '5.0.0'
mod 'puppet-archive', '3.2.1'
mod 'puppet-python', '2.2.2'
mod 'puppet-healthcheck', '0.4.1'
