{
 "title": "Apache",
 "description": "Apache stats for $apache_instance on $server",
 "tags": [
  "apache",
  "collectd"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "query": "collectd.*" },
   { "name": "apache_instance", "label": "apache instance", "query": "collectd.$server.apache.*" }
  ]
 },
 "panels": [
  {
   "title": "Scoreboard",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(collectd.$server.apache.$apache_instance.apache_scoreboard.*)"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$server.apache.$apache_instance.apache_connections, 'connections')"
    }
   ]
  },
  {
   "title": "Idle workers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$server.apache.$apache_instance.apache_idle_workers, 'idle workers')"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$server.apache.$apache_instance.apache_requests, 'requests per second')"
    }
   ]
  },
  {
   "title": "Bytes served",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$server.apache.$apache_instance.apache_bytes, 'bytes served')"
    }
   ]
  }
 ]
}