{
 "title": "CollectD Server Metrics",
 "description": "CollectD & Graphite Server Metrics Dashboard with  CPU, Memory, IO & Disk Stats",
 "tags": [ "collectd" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prefix", "query": "collectd" },
   { "name": "server", "query": "$prefix.*" }
  ]
 },
 "panels": [
  {
   "title": "CPU Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$server.aggregation.cpu-average.cpu.{system,wait,user}, 5)"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$server.memory.memory.{cached,free,buffered}, 4)"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$server.load.load.shortterm, 4)"
    }
   ]
  },
  {
   "title": "Process Fork/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond($prefix.$server.processes.fork_rate), 'new processes')"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$server.processes.ps_state.*, 4)"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond($prefix.$server.disk.*.disk_ops.read), 3)"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond($prefix.$server.disk.*.disk_ops.write), 3)"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$server.df.*.percent_bytes.used, 1, 3)"
    }
   ]
  },
  {
   "title": "Network Traffic/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "alias(scale(perSecond($prefix.$server.interface.*.if_octets.rx), 8), 'in')"
    },
    {
     "target": "alias(scale(perSecond($prefix.$server.interface.*.if_octets.tx), 8), 'out')"
    }
   ]
  },
  {
   "title": "Network Errors/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(perSecond($prefix.$server.interface.*.if_errors.rx), 1), 'in')"
    },
    {
     "target": "alias(removeBelowValue(perSecond($prefix.$server.interface.*.if_errors.tx), 1), 'out')"
    }
   ]
  },
  {
   "title": "Network Packets/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(perSecond($prefix.$server.interface.*.if_packets.rx), 'in')"
    },
    {
     "target": "alias(perSecond($prefix.$server.interface.*.if_packets.tx), 'out')"
    }
   ]
  }
 ]
}